config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :posts, only: %i[index new create] do
    resources :comments, only: [:create]
  end

  resources :follows, only: [:index]
  post 'follows/:id', to: 'follows#create', as: 'follow_user'
  delete 'follows/:id', to: 'follows#destroy', as: 'unfollow_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  parent_id  :bigint
#  post_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_parent_id  (parent_id)
#  index_comments_on_post_id    (post_id)
#  index_comments_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (parent_id => comments.id)
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true

  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  scope :parents, -> { where(parent_id: nil) }
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  follower_id  :bigint           not null
#  following_id :bigint           not null
#
# Indexes
#
#  index_subscriptions_on_follower_id                   (follower_id)
#  index_subscriptions_on_follower_id_and_following_id  (follower_id,following_id) UNIQUE
#  index_subscriptions_on_following_id                  (following_id)
#
# Foreign Keys
#
#  fk_rails_...  (follower_id => users.id)
#  fk_rails_...  (following_id => users.id)
#
class Subscription < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :subscriptions, foreign_key: :follower_id, class_name: 'Subscription'
  has_many :followings, through: :subscriptions, source: :following

  has_many :subscribers, foreign_key: :following_id, class_name: 'Subscription'
  has_many :followers, through: :subscribers, source: :follower

  has_many :comments, dependent: :destroy

  def subscriptions_posts
    Post.where(user: followings.pluck(:id)).order(created_at: :desc)
  end

  def follow(user)
    subscriptions.create(following: user) unless following?(user)
  end

  def unfollow(user)
    subscriptions.find_by(following: user).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.parent_id = params[:parent_id] if params[:parent_id]

    if @comment.save
      redirect_to posts_path
    else
      redirect_to posts_path, alert: 'something wrong'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id)
  end

  def create
    user = User.find(params[:id])
    if current_user.follow(user)
      redirect_to follows_path, notice: "You have subscribed to #{user.email}"
    else
      redirect_to follows_path, alert: 'Something wrong'
    end
  end

  def destroy
    user = User.find(params[:id])
    if current_user.unfollow(user)
      redirect_to follows_path, notice: "You have unsubscribed to #{user.email}"
    else
      redirect_to follows_path, alert: 'Something wrong'
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    if user_signed_in?
      @posts = current_user.subscriptions_posts.includes(:user).order(created_at: :desc)
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def react_component(component_name, props = {}, html_options = {})
    html_options = html_options.with_indifferent_access
    html_options[:id] ||= component_name.parameterize

    tag.div '', **html_options, data: { react_component: component_name, react_props: props.to_json }
  end
end

app/views/comments/_comment.html.slim
.comment
  p
    strong= comment.user.email
    | :
    = comment.content

  p
    = link_to 'Reply', '#', class: 'reply-link', data: { comment_id: comment.id }

  = form_with model: [comment.post, Comment.new], local: true, id: "reply-form-#{comment.id}", class: 'reply-form' do |f|
    = f.hidden_field :parent_id, value: comment.id
    .form-group
      = f.label :content, 'Add reply:'
      = f.text_area :content
    = f.submit 'send'

  - if comment.replies.any?
    .replies
      - comment.replies.each do |reply|
        = render partial: 'comments/comment', locals: { comment: reply }

app/views/comments/_form.html.slim
= form_with model: [post, post.comments.build], local: true do |f|
  .form-group
    = f.label :content, 'Your comment'
    = f.text_area :content, rows: 2

  .form-group
    = f.submit 'Add comment'

app/views/follows/index.html.slim
h1 Users for subscription

- if @users.any?
  - @users.each do |user|
    .user
      p
        strong= user.email

        - if current_user.following?(user)
          = link_to 'Unsubscribe', unfollow_user_path(user), method: :delete
        - else
          = link_to 'Subscribe', follow_user_path(user), method: :post
- else
  p There are no users to subscribe to

= link_to 'Home', root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AADS test project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application.jsx' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.slim
h1 Welcome to the Home Page
- if user_signed_in?
  = link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'button'
  br
  = link_to 'Create a new post', new_post_path
  br
  = link_to 'Find users for subscribe', follows_path

  h2 Following posts

  - if @posts.any?
    - @posts.each do |post|
      .post
        h3 style='color: green'
          = "#{post.content} by -> #{post.user.email}"

        = form_with model: [post, Comment.new], local: true do |f|
          .form-group
            = f.label :content, 'Add comment:'
            = f.text_area :content
          = f.submit 'Send'

        - if post.comments.parents.any?
          .comments
            - post.comments.parents.each do |comment|
              = render partial: 'comments/comment', locals: { comment: comment }

  - else
    p You dont have any posts yet

- else
  = link_to 'Sign up', new_user_registration_path, class: 'button'
  br
  = link_to 'Login', new_user_session_path, class: 'button'

app/views/posts/new.html.slim
h1 Create new post

= form_with model: @post, local: true do |f|
  .form-group
    = f.label :content, 'Text'
    = f.text_area :content, rows: 5

  .form-group
    = f.submit 'Create post'

= link_to 'Home', root_path